<%@ Page Title="My Games" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="MyGames.aspx.cs" Inherits="OldBoardGamesNeedLoveToo.Web.MyGames" %>

<%@ Register Assembly="AjaxControlToolkit"
    Namespace="AjaxControlToolkit"
    TagPrefix="ajaxtoolkit" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="col-md-12">
        <h2>My Games</h2>
        <h5>Review or update your old board games</h5>
        <br />
        <hr />
        <div class="col-md-12 add-game-btn">
            <a href="/addgame.aspx" class="btn btn-primary btn-lg">Add an Old Game</a>
        </div>
        <div class="col-md-12">
            <asp:GridView ID="GridViewMyGames" runat="server"
                ItemType="OldBoardGamesNeedLoveToo.Models.Game"
                SelectMethod="GridViewMyGames_GetData"
                UpdateMethod="GridViewMyGames_UpdateItem"
                DeleteMethod="GridViewMyGames_DeleteItem"
                DataKeyNames="Id"
                AutoGenerateSelectButton="true"
                AutoGenerateDeleteButton="true"
                AutoGenerateEditButton="true"
                AutoGenerateColumns="false" CssClass="table table-responsive table-bordered">
                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <th>Name</th>
                            <th>Desription</th>
                            <th>Contents</th>
                            <th>Categories</th>
                            <th>Condition</th>
                            <th>Minimum Number of Players</th>
                            <th>Maximum Number of Players</th>
                            <th>Minimum Age of Players</th>
                            <th>Maximum Age of Players</th>
                            <th>ReleaseDate</th>
                            <th>Language</th>
                            <th>Producer</th>
                            <th>Price</th>
                            <th>isSold</th>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <tr>
                                <td>
                                    <asp:Image ID="ImageOfGame" runat="server" CssClass="img-thumbnail" ImageUrl='<%# string.Format("data:image/jpeg;base64,{0}", Convert.ToBase64String(Item.Image)) %>' Width="150" />
                                </td>
                                <td><%#: Item.Name %></td>
                                <td><%#: Item.Desription%> </td>
                                <td><%#: Item.Contents%></td>
                                <td><%#: string.Join(" ", Item.Categories) %></td>
                                <td><%#: Item.Condition%></td>
                                <td><%#: Item.MinPlayers%></td>
                                <td><%#: Item.MaxPlayers%></td>
                                <td><%#: Item.MinAgeOfPlayers%></td>
                                <td><%#: Item.MaxAgeOfPlayers%></td>
                                <td><%#: Item.ReleaseDate%></td>
                                <td><%#: Item.Language%></td>
                                <td><%#: Item.Producer%></td>
                                <td><%#: Item.Price%></td>
                                <td><%#: Item.isSold%></td>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <td>
                                <asp:TextBox Text="<%# BindItem.Name %>" runat="server" ID="TextBoxName" />
                            </td>
                            <td>
                                <asp:TextBox Text='<%# BindItem.Desription %>' runat="server" ID="TextBoxDescription" />
                            </td>
                            <td>
                                <asp:TextBox Text='<%# BindItem.Contents %>' runat="server" ID="Contents" />
                            </td>
                            <td>
                                <%--<asp:DropDownList DataTextField="Categories" runat="server" ItemType="OldBoardGamesNeedLoveToo.Models.Category" SelectMethod="ListViewGames_GetCategories" ID="Categories" />--%>
                            </td>
                            <td>
                                <asp:DropDownList runat="server" SelectedValue="<%# BindItem.Condition %>" AutoPostBack="false" ID="DropDownCondition">
                                    <asp:ListItem Value="Excellent">Excellent</asp:ListItem>
                                    <asp:ListItem Value="VeryGood">Very Good</asp:ListItem>
                                    <asp:ListItem Value="Good">Good</asp:ListItem>
                                    <asp:ListItem Value="Poor">Poor</asp:ListItem>
                                    <asp:ListItem Value="VeryPoor">Very Poor</asp:ListItem>
                                </asp:DropDownList>
                            </td>
                            <td>
                                <asp:TextBox Text='<%# BindItem.MinPlayers %>' runat="server" ID="TextBoxMinPlayers" />
                            </td>
                            <td>
                                <asp:TextBox Text='<%# BindItem.MaxPlayers %>' runat="server" ID="TextBoxMaxPlayers" />
                            </td>
                            <td>
                                <asp:TextBox Text='<%# BindItem.MinAgeOfPlayers %>' runat="server" ID="TextBoxMinAgePlayers" />
                            </td>
                            <td>
                                <asp:TextBox Text='<%# BindItem.MaxAgeOfPlayers %>' runat="server" ID="TextBoxMaxAgePlayers" />
                            </td>
                            <td>
                                <asp:TextBox ValidateRequestMode="Disabled" TextMode="DateTime" runat="server" ID="TextBoxDate" Text="<%# BindItem.ReleaseDate %>"></asp:TextBox>
                            </td>
                            <td>
                                <asp:TextBox Text='<%# BindItem.Language %>' runat="server" ID="TextBoxLanguage" />
                            </td>
                            <td>
                                <asp:TextBox Text='<%# BindItem.Producer %>' runat="server" ID="TextBoxProducer" />
                            </td>
                            <td>
                                <asp:TextBox Text='<%# BindItem.Price %>' runat="server" ID="TextBoxPrice" />
                            </td>
                            <td>
                                <asp:CheckBox Checked='<%# BindItem.isSold %>' Text="isSold" runat="server" ID="CheckBoxisSold" />
                            </td>
                            </tr>                            
                        </EditItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>
    </div>
</asp:Content>
