// <auto-generated />
namespace OldBoardGamesNeedLoveToo.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserCustomInfoIdnullabletrue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserCustomInfoIdnullabletrue));
        
        string IMigrationMetadata.Id
        {
            get { return "201702101207422_UserCustomInfoId nullable - true"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
