<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="ManageGames.aspx.cs" Inherits="OldBoardGamesNeedLoveToo.Web.Admin.ManageGames" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView ID="GridViewManageGames" runat="server"
        ItemType="OldBoardGamesNeedLoveToo.Models.Game"
        SelectMethod="GridViewManageGames_GetData"
        UpdateMethod="GridViewManageGames_UpdateItem"
        DeleteMethod="GridViewManageGames_DeleteItem"
        DataKeyNames="Id"
        HeaderStyle-BackColor="AliceBlue"
        AlternatingRowStyle-BackColor="AliceBlue"
        AllowSorting="true"
        AutoGenerateDeleteButton="true"
        AutoGenerateEditButton="true"
        AllowPaging="true" PageSize="10"
        AutoGenerateColumns="false" CssClass="table table-responsive table-bordered">
        <Columns>
            <asp:TemplateField HeaderText="Image">
                <ItemTemplate>
                    <asp:Image ID="GameImage" runat="server" Width="150" ImageUrl='<%# string.Format("data:image/jpeg;base64,{0}", Convert.ToBase64String(Item.Image)) %>' />
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:Image ID="GameImage" runat="server" Width="150" ImageUrl='<%# string.Format("data:image/jpeg;base64,{0}", Convert.ToBase64String(Item.Image)) %>' />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="Name" HeaderText="Name">
                <ItemTemplate>
                    <%#: Item.Name %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Name %>" runat="server" ID="TextBoxName" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Description">
                <ItemTemplate>
                    <%#: Item.Desription %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Desription %>" runat="server" ID="TextBoxDescription" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Contents">
                <ItemTemplate>
                    <%#: Item.Contents %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Contents %>" runat="server" ID="TextBoxContents" />
                </EditItemTemplate>
            </asp:TemplateField>
            <%--<asp:TemplateField HeaderText="Categories">
                        <ItemTemplate>
                            <%#: string.Join(" ", Item.Categories) %>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox Text="<%# BindItem.Categories %>" runat="server" ID="TextBoxcategories" />
                        </EditItemTemplate>
                    </asp:TemplateField>--%>
            <asp:TemplateField HeaderText="Condition" SortExpression="Condition">
                        <ItemTemplate>
                            <%# Item.Condition %>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:DropDownList runat="server" SelectedValue="<%# BindItem.Condition %>" AutoPostBack="false" ID="DropDownCondition">
                                <asp:ListItem Value="Excellent">Excellent</asp:ListItem>
                                <asp:ListItem Value="VeryGood">Very Good</asp:ListItem>
                                <asp:ListItem Value="Good">Good</asp:ListItem>
                                <asp:ListItem Value="Poor">Poor</asp:ListItem>
                                <asp:ListItem Value="VeryPoor">Very Poor</asp:ListItem>
                            </asp:DropDownList>
                        </EditItemTemplate>
                    </asp:TemplateField>
            <asp:TemplateField HeaderText="Minimum Number Of Players" SortExpression="MinPlayers">
                <ItemTemplate>
                    <%#: Item.MinPlayers %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.MinPlayers %>" runat="server" ID="TextBoxMinPlayers" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="MaxPlayers" HeaderText="Maximum Number Of Players">
                <ItemTemplate>
                    <%#: Item.MaxPlayers %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.MaxPlayers %>" runat="server" ID="TextBoxmaxPlayers" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="MinAgeOfPlayers" HeaderText="Minimum Age Of Players">
                <ItemTemplate>
                    <%#: Item.MinAgeOfPlayers %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.MinAgeOfPlayers %>" runat="server" ID="TextBoxMinAgeOfPlayers" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="MaxAgeOfPlayers" HeaderText="Maximum Age Of Players">
                <ItemTemplate>
                    <%#: Item.MaxAgeOfPlayers %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.MaxAgeOfPlayers %>" runat="server" ID="TextBoxMaxAgeOfPlayers" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="ReleaseDate" HeaderText="Release Date">
                <ItemTemplate>
                    <%#: Item.ReleaseDate %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.ReleaseDate %>" runat="server" ID="TextBoxReleaseDate" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="Language" HeaderText="Language">
                <ItemTemplate>
                    <%#: Item.Language %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Language %>" runat="server" ID="TextBoxLanguage" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="Producer" HeaderText="Producer">
                <ItemTemplate>
                    <%#: Item.Producer %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Producer %>" runat="server" ID="TextBoxProducer" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="Price" HeaderText="Price">
                <ItemTemplate>
                    <%#: Item.Price %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Price %>" runat="server" ID="TextBoxPrice" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="isSold" HeaderText="isSold">
                <ItemTemplate>
                    <%#: Item.isSold %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:CheckBox Checked="<%# BindItem.isSold %>" runat="server"  ID="CheckBoxBoxisSold" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="OwnerId" HeaderText="OwnerId">
                <ItemTemplate>
                    <%#: Item.OwnerId %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.OwnerId %>" runat="server" ID="TextBoxOwnerId" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="BuyerId" HeaderText="BuyerId">
                <ItemTemplate>
                    <%#: Item.BuyerId %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.BuyerId %>" runat="server" ID="TextBoxBuyerId" />
                </EditItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
</asp:Content>
