<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ManageCategories.aspx.cs" Inherits="OldBoardGamesNeedLoveToo.Web.Admin.ManageCategories" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView ID="GridViewManageCategories" runat="server"
        ItemType="OldBoardGamesNeedLoveToo.Models.Category"
        SelectMethod="GridViewManageCategories_GetData"
        UpdateMethod="GridViewManageCategories_UpdateItem"
        DeleteMethod="GridViewManageCategories_DeleteItem"
        DataKeyNames="Id"
        HeaderStyle-BackColor="AliceBlue"
        AlternatingRowStyle-BackColor="AliceBlue"
        AllowSorting="true"
        AutoGenerateDeleteButton="true"
        AutoGenerateEditButton="true"
        AllowPaging="true" PageSize="10"
        AutoGenerateColumns="false" CssClass="table table-responsive table-bordered">
        <Columns>
            <asp:TemplateField SortExpression="Name" HeaderText="Name">
                <ItemTemplate>
                    <%#: Item.Name %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Name %>" runat="server" ID="TextBoxName" />
                </EditItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
    <asp:Button runat="server" Text="Add" OnClick="AddCategory_Click" ID="AddCategory"></asp:Button>
    <asp:TextBox runat="server" ID="CategoryName"></asp:TextBox>

</asp:Content>
