<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ManageUsers.aspx.cs" Inherits="OldBoardGamesNeedLoveToo.Web.Admin.ManageUsers" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView ID="GridViewManageUsers" runat="server"
        ItemType="OldBoardGamesNeedLoveToo.Models.UserCustomInfo"
        SelectMethod="GridViewManageUsers_GetData"
        UpdateMethod="GridViewManageUsers_UpdateItem"
        DeleteMethod="GridViewManageUsers_DeleteItem"
        DataKeyNames="Id"
        HeaderStyle-BackColor="AliceBlue"
        AlternatingRowStyle-BackColor="AliceBlue"
        AllowSorting="true"
        AutoGenerateDeleteButton="true"
        AutoGenerateEditButton="true"
        AllowPaging="true" PageSize="10"
        AutoGenerateColumns="false" CssClass="table table-responsive table-bordered">
        <Columns>
            <asp:TemplateField SortExpression="Role" HeaderText="Role">
                <ItemTemplate>
                    <%#: Item.Role%>
                </ItemTemplate>
                <EditItemTemplate>
                    <%#: Item.Role %>
                    <%--<asp:TextBox Text="<%# BindItem.Username %>" runat="server" ID="TextBoxRole" />--%>
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="Username" HeaderText="Username">
                <ItemTemplate>
                    <%#: Item.Username %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Username %>" runat="server" ID="TextBoxUsername" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="FirstName" HeaderText="FirstName">
                <ItemTemplate>
                    <%#: Item.FirstName %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.FirstName %>" runat="server" ID="TextBoxFirstName" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="LastName" HeaderText="LastName">
                <ItemTemplate>
                    <%#: Item.LastName %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.LastName %>" runat="server" ID="TextBoxLastName" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="Email" HeaderText="Email">
                <ItemTemplate>
                    <%#: Item.Email %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Email %>" runat="server" ID="TextBoxEmail" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="Phone" HeaderText="Phone">
                <ItemTemplate>
                    <%#: Item.Phone %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Phone %>" runat="server" ID="TextBoxPhone" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="Address" HeaderText="Address">
                <ItemTemplate>
                    <%#: Item.Address %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Address %>" runat="server" ID="TextBoxAddress" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="AverageRatingResult" HeaderText="AverageRatingResult">
                <ItemTemplate>
                    <%#: Item.AverageRatingResult %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.AverageRatingResult %>" runat="server" ID="TextBoxAverageRatingResult" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="NumberOfUsersGivenRating" HeaderText="NumberOfUsersGivenRating">
                <ItemTemplate>
                    <%#: Item.NumberOfUsersGivenRating %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.NumberOfUsersGivenRating %>" runat="server" ID="TextBoxNumberOfUsersGivenRating" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="SumOfUsersRating" HeaderText="SumOfUsersRating">
                <ItemTemplate>
                    <%#: Item.SumOfUsersRating %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.SumOfUsersRating %>" runat="server" ID="TextBoxSumOfUsersRating" />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="ProfilePicture">
                <ItemTemplate>
                    <asp:Image ID="ProfilePicture" runat="server" Width="150" ImageUrl='<%# string.Format("data:image/jpeg;base64,{0}", Convert.ToBase64String(Item.ProfilePricture)) %>' />
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:Image ID="ProfilePicture" runat="server" Width="150" ImageUrl='<%# string.Format("data:image/jpeg;base64,{0}", Convert.ToBase64String(Item.ProfilePricture)) %>' />
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="SellingGames">
                <ItemTemplate>
                    <%#: string.Join(" ",Item.SellingGames )%>
                </ItemTemplate>
                <EditItemTemplate>
                    <%#: string.Join(" ",Item.SellingGames )%>
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="BoughtGames">
                <ItemTemplate>
                    <%#: string.Join(" ",Item.BoughtGames)%>
                </ItemTemplate>
                <EditItemTemplate>
                    <%#: string.Join(" ",Item.BoughtGames)%>
                </EditItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
</asp:Content>
