<%@ Page Title="Manage Games" Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="ManageGames.aspx.cs" Inherits="OldBoardGamesNeedLoveToo.Web.Admin.ManageGames" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView ID="GridViewManageGames" runat="server"
        ItemType="OldBoardGamesNeedLoveToo.Models.Game"
        SelectMethod="GridViewManageGames_GetData"
        UpdateMethod="GridViewManageGames_UpdateItem"
        DeleteMethod="GridViewManageGames_DeleteItem"
        DataKeyNames="Id"
        HeaderStyle-BackColor="AliceBlue"
        AlternatingRowStyle-BackColor="AliceBlue"
        AllowSorting="true"
        AutoGenerateDeleteButton="true"
        AutoGenerateEditButton="true"
        AllowPaging="true" PageSize="10" ShowFooter="true"
        AutoGenerateColumns="false" CssClass="table table-responsive table-bordered">
        <Columns>
            <asp:TemplateField HeaderText="Image">
                <ItemTemplate>
                    <asp:Image ID="GameImage" runat="server" Width="150" ImageUrl='<%# string.Format("data:image/jpeg;base64,{0}", Convert.ToBase64String(Item.Image)) %>' />
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:Image ID="GameImage" runat="server" Width="150" ImageUrl='<%# string.Format("data:image/jpeg;base64,{0}", Convert.ToBase64String(Item.Image)) %>' />
                </EditItemTemplate>
<%--                <FooterTemplate>
                    <asp:FileUpload ID="FileUploadGameImage" runat="server"  CssClass="btn btn-file input"/>
                </FooterTemplate>--%>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="Name" HeaderText="Name" InsertVisible="true">
                <ItemTemplate>
                    <%#: Item.Name %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Name %>" runat="server" ID="TextBoxName" />
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:TextBox Text="<%# BindItem.Name %>" runat="server" ID="TextBoxName" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Description" InsertVisible="true">
                <ItemTemplate>
                    <%#: Item.Desription %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Desription %>" runat="server" ID="TextBoxDescription" />
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:TextBox Text="<%# BindItem.Desription %>" runat="server" ID="TextBoxDescription" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Contents" InsertVisible="true">
                <ItemTemplate>
                    <%#: Item.Contents %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Contents %>" runat="server" ID="TextBoxContents" />
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:TextBox Text="<%# BindItem.Contents %>" runat="server" ID="TextBoxContents" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Categories" InsertVisible="true">
                <ItemTemplate>
                    <asp:Repeater ID="RepeaterGameCategories" runat="server" DataSource="<%# Item.Categories %>" ItemType="OldBoardGamesNeedLoveToo.Models.Category">
                        <ItemTemplate>
                            <%#: string.Format(" {0}", Item.Name) %>
                        </ItemTemplate>
                    </asp:Repeater>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:Repeater ID="RepeaterGameCategories" runat="server" DataSource="<%# Item.Categories %>" ItemType="OldBoardGamesNeedLoveToo.Models.Category">
                        <ItemTemplate>
                            <%#: string.Format(" {0}", Item.Name) %>
                        </ItemTemplate>
                    </asp:Repeater>
                    <%--<asp:DropDownList ID="DropDownListCategory" runat="server" DataTextField="Name" DataValueField="Id"></asp:DropDownList>--%>
                </EditItemTemplate>
                <FooterTemplate>
                    <%--<asp:DropDownList runat="server" ID="DropDownCategories" ItemType="OldBoardGamesNeedLoveToo.Models.Category"></asp:DropDownList>--%>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Condition" SortExpression="Condition" InsertVisible="true">
                <ItemTemplate>
                    <%# Item.Condition %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:DropDownList runat="server" SelectedValue="<%# BindItem.Condition %>" AutoPostBack="false" ID="DropDownCondition">
                        <asp:ListItem Value="Excellent">Excellent</asp:ListItem>
                        <asp:ListItem Value="VeryGood">Very Good</asp:ListItem>
                        <asp:ListItem Value="Good">Good</asp:ListItem>
                        <asp:ListItem Value="Poor">Poor</asp:ListItem>
                        <asp:ListItem Value="VeryPoor">Very Poor</asp:ListItem>
                    </asp:DropDownList>
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:DropDownList runat="server" SelectedValue="<%# BindItem.Condition %>" AutoPostBack="false" ID="DropDownCondition">
                        <asp:ListItem Value="Excellent">Excellent</asp:ListItem>
                        <asp:ListItem Value="VeryGood">Very Good</asp:ListItem>
                        <asp:ListItem Value="Good">Good</asp:ListItem>
                        <asp:ListItem Value="Poor">Poor</asp:ListItem>
                        <asp:ListItem Value="VeryPoor">Very Poor</asp:ListItem>
                    </asp:DropDownList>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Minimum Number Of Players" SortExpression="MinPlayers" InsertVisible="true">
                <ItemTemplate>
                    <%#: Item.MinPlayers %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.MinPlayers %>" runat="server" ID="TextBoxMinPlayers" />
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:TextBox Text="<%# BindItem.MinPlayers %>" runat="server" ID="TextBoxMinPlayers" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="MaxPlayers" HeaderText="Maximum Number Of Players" InsertVisible="true">
                <ItemTemplate>
                    <%#: Item.MaxPlayers %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.MaxPlayers %>" runat="server" ID="TextBoxmaxPlayers" />
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:TextBox Text="<%# BindItem.MaxPlayers %>" runat="server" ID="TextBoxmaxPlayers" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="MinAgeOfPlayers" HeaderText="Minimum Age Of Players">
                <ItemTemplate>
                    <%#: Item.MinAgeOfPlayers %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.MinAgeOfPlayers %>" runat="server" ID="TextBoxMinAgeOfPlayers" />
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:TextBox Text="<%# BindItem.MinAgeOfPlayers %>" runat="server" ID="TextBoxMinAgeOfPlayers" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="MaxAgeOfPlayers" HeaderText="Maximum Age Of Players" InsertVisible="true">
                <ItemTemplate>
                    <%#: Item.MaxAgeOfPlayers %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.MaxAgeOfPlayers %>" runat="server" ID="TextBoxMaxAgeOfPlayers" />
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:TextBox Text="<%# BindItem.MaxAgeOfPlayers %>" runat="server" ID="TextBoxMaxAgeOfPlayers" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="ReleaseDate" HeaderText="Release Date">
                <ItemTemplate>
                    <%#: Item.ReleaseDate %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.ReleaseDate %>" runat="server" ID="TextBoxReleaseDate" />
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:TextBox TextMode="Date" Text="<%# BindItem.ReleaseDate %>" runat="server" ID="TextBoxReleaseDate" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="Language" HeaderText="Language" InsertVisible="true">
                <ItemTemplate>
                    <%#: Item.Language %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Language %>" runat="server" ID="TextBoxLanguage" />
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:TextBox Text="<%# BindItem.Language %>" runat="server" ID="TextBoxLanguage" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="Producer" HeaderText="Producer">
                <ItemTemplate>
                    <%#: Item.Producer %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Producer %>" runat="server" ID="TextBoxProducer" />
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:TextBox Text="<%# BindItem.Producer %>" runat="server" ID="TextBoxProducer" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="Price" HeaderText="Price" InsertVisible="true">
                <ItemTemplate>
                    <%#: string.Format("{0:c}", Item.Price) %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.Price %>" runat="server" ID="TextBoxPrice" />
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:TextBox Text="<%# BindItem.Price %>" runat="server" ID="TextBoxPrice" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="isSold" HeaderText="isSold" InsertVisible="true">
                <ItemTemplate>
                    <%#: Item.isSold %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:CheckBox Checked="<%# BindItem.isSold %>" runat="server" ID="CheckBoxBoxisSold" />
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:CheckBox Checked="<%# BindItem.isSold %>" runat="server" ID="CheckBoxBoxisSold" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="OwnerId" HeaderText="OwnerId">
                <ItemTemplate>
                    <%#: Item.OwnerId %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.OwnerId %>" runat="server" ID="TextBoxOwnerId" />
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:TextBox Text="<%# BindItem.OwnerId %>" runat="server" ID="TextBoxOwnerId" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="BuyerId" HeaderText="BuyerId" InsertVisible="true">
                <ItemTemplate>
                    <%#: Item.BuyerId %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox Text="<%# BindItem.BuyerId %>" runat="server" ID="TextBoxBuyerId" />
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:TextBox Text="<%# BindItem.BuyerId %>" runat="server" ID="TextBoxBuyerId" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField>
                <FooterTemplate>
                    <asp:Button ID="ButtonAdd" runat="server" Text="Insert" CommandName="Insert" CssClass="btn btn-default"/>
                </FooterTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>

    <hr />
    <div class="col-md-12 add-game-btn">
        <a href="/addgame.aspx" class="btn btn-primary btn-lg">Add a Game as User</a>
    </div>
</asp:Content>
