// <auto-generated />
namespace OldBoardGamesNeedLoveToo.Auth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UserCustomInfoAverageRatingChangedToNullableType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserCustomInfoAverageRatingChangedToNullableType));
        
        string IMigrationMetadata.Id
        {
            get { return "201702191651241_UserCustomInfo AverageRating Changed To Nullable Type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
